# Site setings
include: ['_pages', '_data','_tools']
name: "KR Toolbox"
logo:
mailchimp_url: ""
-scope:
  path: ""
  values:
    layout: default
    _options:
      content: &content_defaults
        uploads_dir: "uploads/:title"
        format: p h1 h2 h3 h4 h5 h6 div
        styles: /assets/css/theme.css
        undo: true
        redo: true
        left: text-left
        center: text-center
        right: text-right
        justify: justify-content-center
        bold: true
        italic: true
        underline: true
        strike: true
        subscript: false
        superscript: false
        blockquote: true
        table: true
        copyformatting: true
        removeformat: true
        numberedlist: true
        bulletedlist: true
        outdent: false
        indent: false
        image: true
        link: true
        embed: true
collections:
        tools:
          output: true
          order:
          - maison-mouton.md
          - nickerson-house.md
          - esprit-de-coeur.md
          - feed-n-seed.md
-scope:
  type: pages
  path: _pages/index.html
  values:
    permalink: 
-scope:
path: "_tools"
type: "page"
values:
layout: "tools"
amp:
addthis: true  # layout level
iframe: true   # layout level
script: true   # layout level
gist: true     # page level
youtube: true  # page level
# Required Plugins
plugins:
  # - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Sass
sass:
  sass_dir: _sass
  style: compressed
