# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Jekyll

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
data:
  path: _data
  output: false
posts:
  path: _posts
  output: true
  create:
    path: >-
      [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
pages:
  path: ''
  output: true
  filter: strict
tools:
  output: true
  path: _tools
_select_data:
  location:
    type: select
    options:
      values:
        - Esprit de Coeur
        - Feed N Seed
        - The John Nickerson House
_inputs:
  image_2:
    type: image
  image_3:
    type: image
  start:
    type: date
  end:
    type: date
  event-description:
    type: markdown
  Bio:
    type: markdown
  location:
    type: select
    options:
      values:
        - Esprit de Coeur
        - Feed N Seed
        - The John Nickerson House
  categories:
    type: select
    options:
      values:
        - article
        - history
_editables:
    block:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      underline: true
      link: true
      bulletedlist: true
      indent: true
      numberedlist: true
      code: true
      embed: true
      image: true
      table: true
      styles: /assets/css/index.bundle.css
      left: text-left
      center: text-center
      right: text-right
      image_size_attributes: false
      expandable: true
      resize_style: cover
    content:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      underline: true
      link: true
      bulletedlist: true
      indent: true
      numberedlist: true
      code: true
      embed: true
      image: true
      table: true
      redo: true 
      image_size_attributes: false
      expandable: true
      removeformat: true
      copyformatting: true 
      resize_style: cover
      styles: /assets/css/index.bundle.css
      left: text-left
      center: text-center
      right: text-right
    sub-page:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      underline: true
      link: true
      bulletedlist: true
      indent: true
      numberedlist: true
      code: true
      embed: true
      image: true
      table: true
      redo: true 
      image_size_attributes: false
      expandable: true
      removeformat: true
      copyformatting: true 
      resize_style: cover
      styles: /assets/css/index.bundle.css
      left: text-left
      center: text-center
      right: text-right
    description:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      underline: true
      link: true
      bulletedlist: true
      indent: true
      numberedlist: true
      code: true
      embed: true
      image: true
      table: true
      redo: true 
      image_size_attributes: false
      expandable: true
      removeformat: true
      copyformatting: true 
      resize_style: cover
      styles: /assets/css/index.bundle.css
      left: text-left
      center: text-center
      right: text-right
_enabled_editors:
      - visual
      - data
collections_config:
      posts:
        _enabled_editors:
          - content
          - visual
          - data
# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:

# Set this to true to disable auto-detection of collections.
collections_config_override: false


# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: _data
  collections: ''
  layouts: _layouts
  static: ''
  uploads: uploads
  includes: _includes
  dam_uploads: ''
  dam_static: ''

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: CST
